<?php

namespace ContainerKY5xpRJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DwdKY9rService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dwdKY9r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dwdKY9r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'itinerary' => ['privates', '.errored..service_locator.dwdKY9r.App\\Entity\\Itinerary', NULL, 'Cannot autowire service ".service_locator.dwdKY9r": it references class "App\\Entity\\Itinerary" but no such service exists.'],
        ], [
            'itinerary' => 'App\\Entity\\Itinerary',
        ]);
    }
}
