<?php

namespace Container0Fkl6xp;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I7Z4iXcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i7Z4iXc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i7Z4iXc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'itinerary' => ['privates', '.errored..service_locator.i7Z4iXc.App\\Entity\\Itinerary', NULL, 'Cannot autowire service ".service_locator.i7Z4iXc": it references class "App\\Entity\\Itinerary" but no such service exists.'],
            'itineraryRepository' => ['privates', 'App\\Repository\\ItineraryRepository', 'getItineraryRepositoryService', true],
        ], [
            'itinerary' => 'App\\Entity\\Itinerary',
            'itineraryRepository' => 'App\\Repository\\ItineraryRepository',
        ]);
    }
}
