<?php

namespace Container0Fkl6xp;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GNsQvUCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GNsQvUC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GNsQvUC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'itineraryRepository' => ['privates', 'App\\Repository\\ItineraryRepository', 'getItineraryRepositoryService', true],
        ], [
            'itineraryRepository' => 'App\\Repository\\ItineraryRepository',
        ]);
    }
}
