<?php

namespace Container0Fkl6xp;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItinerary2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.i7Z4iXc.App\Entity\Itinerary' shared service.
     *
     * @return \App\Entity\Itinerary
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.i7Z4iXc": it references class "App\\Entity\\Itinerary" but no such service exists.');
    }
}
