<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0Fkl6xp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0Fkl6xp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0Fkl6xp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0Fkl6xp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0Fkl6xp\App_KernelDevDebugContainer([
    'container.build_hash' => '0Fkl6xp',
    'container.build_id' => 'c859fb5d',
    'container.build_time' => 1678975185,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0Fkl6xp');
