<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKY5xpRJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKY5xpRJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKY5xpRJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKY5xpRJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKY5xpRJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'KY5xpRJ',
    'container.build_id' => '09d11cc3',
    'container.build_time' => 1678982228,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKY5xpRJ');
