#index:
#    path: /
#    controller: App\Controller\DefaultController::index
itinerary_index:
    path: /itinerary
    controller: App\Controller\ItineraryController::index
    
user_index:
  path: /user
  controller: App\Controller\ItineraryController::index